name: Garage Door Repair Bellevue
favicon: null
layout_spectrum: 0.97563
typography_spectrum: 0.9205171312205493
title: 'Garage Door Repair Bellevue, WA'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9e0e8'
    - '#000000'
    - '#8d9095'
    - '#454640'
    - '#666666'
  brandStrength: 0.7723143068142235
  lightness: 0.6471271398477256
  saturation: 0.13492035097442567
  rhythmicContrast: 0.5409426931291819
purpose: []
