name: Garage Door Repair Bellevue
favicon: null
layout_spectrum: 0.5289213256910443
typography_spectrum: 0.1443505093920976
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8211334936786443
  lightness: 0.3882276504300535
  saturation: 0.06541435606777668
  rhythmicContrast: 0.14728547120466828
purpose: []
