name: Garage Door Repair Bellevue
favicon: null
layout_spectrum: 1
typography_spectrum: 0.85393
title: 'Garage Door Repair Bellevue, WA'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1394b5'
    - '#000000'
    - '#00ffff'
    - '#0000ff'
    - '#0055aa'
  brandStrength: 0.875
  lightness: 0.6471271398477256
  saturation: 0.13492035097442567
  rhythmicContrast: 0.5409426931291819
purpose: []
