name: Garage Door Repair Bellevue
favicon: null
layout_spectrum: 0.9819625043310225
typography_spectrum: 0.21636667591519654
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7172088138759136
  lightness: 0.33903689077124
  saturation: 0.38715687626972795
  rhythmicContrast: 0.4133234126493335
purpose: []
