name: Garage Door Repair Bellevue
favicon: null
layout_spectrum: 0.3404893351253122
typography_spectrum: 0.7152263012249023
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.40537153533659875
  lightness: 0.4338915429543704
  saturation: 0.46927072387188673
  rhythmicContrast: 0.06973705952987075
purpose: []
