name: Garage Door Repair Bellevue
favicon: null
layout_spectrum: 0.2426220786292106
typography_spectrum: 0.36303376965224743
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5659300156403333
  lightness: 0.12026445241644979
  saturation: 0.5685873639304191
  rhythmicContrast: 0.567917411448434
purpose: []
