name: Garage Door Repair Bellevue
favicon: null
layout_spectrum: 0.5774656478315592
typography_spectrum: 0.07883611903525889
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5650469451211393
  lightness: 0.8692467983346432
  saturation: 0.6371202543377876
  rhythmicContrast: 0.2535004315432161
purpose: []
